### ISSUE TITLE
Move music from room to room.

### ISSUE THREAD

**Issue by mashtonian** [pascalopitz/unoffical-sonos-controller-for-linux#80] opened 2020-06-02 07:39 UTC
One use casde I have, that only works intermittently on the official controller and not at all on this one, is moving of music from room to room.

Expected behaviour:

select a room that is playing something and open the grouping dialog.
unselect the "origin" room and select the "destination" room.

The origin room should stop playing (maybe clear the item from the queue? unsure) and the destination room should pick up.

Essentially it should group the two rooms together then remove the origin room from the group.

In fact, on trying this grouping seems to be a bit broken in general:

I would expect, when selcting the group button on a room, for the music playing in THAT room to be the one grouped to the extra rooms selected. This did not happen just now. It moved the usic playing in the ADDED room into the room on which the group button was pushed.

I use griouping a lot as I move around the house. If it worked perfectly it would be brilliant.

**Comment by pascalopitz** [comment] 2020-06-02 12:11
Grouping is tough, as it behaves weirdly. You basically tell sonos what to group, and it'll do _something_ ... sometimes half of it, sometimes something in two steps ... it's weird. I'll look into it a bit more but my hopes for this one are low :(

**Comment by pascalopitz** [comment] 2020-06-13 12:06
I had a look at this. I think it's fixed as per https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/commit/819bc5ab1529dbe8322b72b5dfd08bdc1b6c9c2b.

The behaviour has changed such that the group you clicked on always will be the playlist source, even if you unselect all the players and move to other ones. Is this what you had in mind?

**Comment by mashtonian** [comment] 2020-06-15 11:45
Yeah, that sounds good.

Will test later.

**Comment by svrooij** [comment] 2020-07-01 16:22
Might be that the controller is sending [this](https://svrooij.github.io/node-sonos-ts/sonos-device/services/avtransportservice.html#becomegroupcoordinator) command, which isn’t available in node-sonos (I believe). The name suggests that it can actually do what you want.

**Comment by pascalopitz** [comment] 2020-07-01 20:58
@svrooij I think it was just a matter of grouping to the wrong device, and I _think_ it works well now. Just that @mashtonian hasn't confirmed, that's why this ticket is hanging.

**Comment by pascalopitz** [comment] 2020-08-19 04:55
Closing this due to lack of reply

**Closed by pascalopitz** 2020-08-19 04:55 UTC
