### ISSUE TITLE
Searching for your Sonos system - forever...

### ISSUE THREAD

**Issue by hertzli** [pascalopitz/unoffical-sonos-controller-for-linux#113] opened 2020-09-22 19:48 UTC
Ubuntu version:

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

Unofficial-sonos-controller installed via SNAP today.

On first run - and on each restart, the app keeps searching for my Sonos system. Menu is working. Restart of app doesn't help, neither does a machine reboot.

App status (Menu -> Developer -> Copy app state to clipboard):
{
    "appState": {
        "sonosService": {
            "currentGroup": null,
            "currentHost": null,
            "zones": [],
            "deviceSearches": {},
            "albumArtCache": {},
            "currentTracks": {},
            "nextTracks": {},
            "positionInfos": {},
            "playStates": {},
            "playModes": {},
            "crossFadeModes": {}
        },
        "groupManagement": {
            "selected": [],
            "visible": false,
            "current": null
        },
        "currentTrack": {
            "expanded": true
        },
        "volume": {
            "dragging": false,
            "expanded": false,
            "volume": {},
            "muted": {}
        },
        "queue": {
            "currentHost": null,
            "currentGroup": null,
            "playerItems": {},
            "selected": []
        },
        "browserList": {
            "source": null,
            "searchTerm": null,
            "searchMode": "artists",
            "history": [
                {
                    "source": "start",
                    "searchType": null,
                    "title": "Select a Music Source",
                    "items": [
                        {
                            "title": "Sonos Favourites",
                            "searchType": "FV:2",
                            "albumArtURI": "./svg/ic_favorite_48px.svg"
                        },
                        {
                            "title": "Music Library",
                            "action": "library",
                            "albumArtURI": "./svg/ic_audiotrack_48px.svg"
                        },
                        {
                            "title": "Sonos Playlists",
                            "searchType": "SQ:",
                            "albumArtURI": "./svg/ic_featured_play_list_48px.svg"
                        },
                        {
                            "title": "Line-in",
                            "action": "linein",
                            "albumArtURI": "./svg/ic_input_48px.svg"
                        }
                    ]
                }
            ]
        },
        "musicServices": {
            "active": [],
            "visible": false,
            "link": null,
            "current": null
        },
        "playlists": {
            "mode": null,
            "visible": false,
            "item": null,
            "playlists": [],
            "selected": [],
            "items": []
        },
        "eq": {
            "visible": false,
            "host": null,
            "eqState": {}
        }
    },
    "packageJson": {
        "name": "sonos-controller-unofficial",
        "description": "Unoffical sonos controller for linux.",
        "version": "0.2.1-alpha7",
        "author": "Pascal Opitz <contact@pascalopitz.com>",
        "main": "main.js",
        "dependencies": {
            "array-union": "^2.0.0",
            "axios": "^0.19.2",
            "bluebird": "^3.5.4",
            "classnames": "^2.2.6",
            "deep-equal": "^2.0.3",
            "dotenv": "^8.2.0",
            "electron-prompt": "^1.6.0",
            "file-type": "^14.7.1",
            "ip": "^1.1.5",
            "koa": "^2.13.0",
            "koa-bodyparser": "^4.3.0",
            "koa-logger": "^3.2.1",
            "koa-router": "^9.4.0",
            "lodash": "^4.17.20",
            "mask-json": "^1.0.3",
            "mime": "^2.4.6",
            "moment": "^2.27.0",
            "music-metadata": "^7.0.1",
            "omit-keys": "^0.1.0",
            "react": "^16.13.1",
            "react-dom": "^16.13.1",
            "react-redux": "^7.2.1",
            "react-tiny-virtual-list": "^2.2.0",
            "react-viewport-list": "^3.0.0",
            "react-virtual-list": "^2.3.0",
            "react-virtualized-auto-sizer": "^1.0.2",
            "redux": "^4.0.1",
            "redux-actions": "^2.6.5",
            "redux-promise": "^0.6.0",
            "reselect": "^4.0.0",
            "shallow-compare": "^1.2.2",
            "sonos": "^1.14.0",
            "sql.js": "^1.3.0",
            "uuid": "^8.3.0",
            "wake-event": "^0.0.1",
            "walkdir": "^0.4.1"
        }
    }
}

**Comment by pascalopitz** [comment] 2020-09-22 22:11
A few things you could try:

- Does the appimage version work?
- Did you check your firewall settings?
- Have you tried manually adding a Player's IP?

**Comment by pascalopitz** [comment] 2020-09-22 22:14
Duplicate of #105

**Closed by pascalopitz** 2020-09-22 22:14 UTC
