### ISSUE TITLE
Deezer impossible connect ( UK / FR)

### ISSUE THREAD

**Issue by RhumDiplomatico** [pascalopitz/unoffical-sonos-controller-for-linux#18] opened 2017-01-21 21:10 UTC
With the Sonos controller v0.0.9-alpha3
    Hello i can not connect my service Deezer under Linux Mint 18.1, pity there is only this problem because everything else works well
    Thank you for trying to help me

    avec le Sonos controleur v0.0.9-alpha3
    bonjour je n'arrive pas à connecter mon service Deezer sous Linux Mint 18.1 , dommage il n'y a que ce problème car tout le reste fonctionne bien.
    Merci d'essayer de me depanner

**Comment by MaxJonasG** [comment] 2017-02-18 10:48
I have the same problem with a UK deezer account. I can put in username and password but when clicking on "next" nothing happens.
The console message is:
`Uncaught (in promise) TypeError: Cannot read property 'Body' of undefined(…)
_doRequest.then.res @ MusicServiceClient.js:369
_tickCallback @ internal/process/next_tick.js:103`

which means that the error is somewhere here in the "let obj" row:
`return this._doRequest(this._serviceDefinition.SecureUri, 'getSessionId', body, headers)
.then((res) => {
let resp = xml2json(stripNamespaces(res));
let obj = resp['Envelope']['Body']['getSessionIdResponse']['getSessionIdResult'];
return obj;`	

but that is all I could see so far. Are the other music services working or is it just deezer that is broken?

**Comment by pascalopitz** [comment] 2017-02-18 12:28
I don't have a Deezer account, thus cannot debug it. Can you set a breakpoint and find out what the response payload it?

**Comment by MaxJonasG** [comment] 2017-02-18 15:59
I would love to but I'm not really someone who knows how to do this. I'll try my best though. are you looking for some specific information? 
Also: are the other services working? I.e. are we looking for a deezer specific problem or is this a general issue?

**Comment by MaxJonasG** [comment] 2017-02-18 18:13
If I set a break point at row 360 I can see that the "RUNTIME ID" is "pascal-sonos-app" and "deviceprovidername" is "SonosControllerForChrome", I guess that is not the problem though. "body" is "undefined", that is what the error message is saying as well.  "res" is also empty

**Comment by MaxJonasG** [comment] 2017-02-19 18:11
I hope this is not considered spamming. I set a breakpoint at row 360 and in row 20. In row 20 "body" and "header" are not empty. (note: the passowrd and username are obviously not my real ones) but that data is not transferred to later in the process.
![screenshot from 2017-02-19 18-08-00](https://cloud.githubusercontent.com/assets/25565941/23104921/cb618a9a-f6ce-11e6-9a85-954c8a89f6cc.png)

![screenshot from 2017-02-19 18-05-43](https://cloud.githubusercontent.com/assets/25565941/23104923/cd13d406-f6ce-11e6-8f14-404c52d5bbca.png)

**Comment by MaxJonasG** [comment] 2017-04-24 20:03
so has anyone else looked into this? latest observation from me is this line in src/ui\actions\\*BrowserListActions

```
const ALLOWED_SERVICES = [12, 160, 201, 17]; // 12 is spotify, 160 soundcloud, 201 Amazon Music
		let sonos = SonosService._currentDevice;
		let existingIds = SonosService._musicServices.map(s => s.service.Id);
```

**Comment by pascalopitz** [comment] 2017-07-16 06:10
Can you try this one again, I have made changes to Auth and Useragents, and think this might be affected

**Comment by RhumDiplomatico** [comment] 2017-08-04 16:48
Bonjour
j'ai refait des essaisde connection , rien ne se passe apres le clic sur OK !?
merci

HI
I have tried again connection, nothing happens after the' clic ' OK button !?
regards

**Comment by MaxJonasG** [comment] 2017-08-13 12:00
I just installed the latest beta. While nothing seems to happen once you click "OK" it actually does authenticate you. I now have 6 Deezer buttons in the bar on the right and can select Tracks from deezer

**Comment by pascalopitz** [comment] 2017-08-13 12:32
Which version exactly?
Can you try the search  function as well please?

Any suggestion as to how we can improve the user experience? What did you
expect to happen when the service got authenticated?

**Comment by MaxJonasG** [comment] 2017-08-13 15:42
Hi Pascal,
I installed v0.1.0-alpha3 (Ubuntu Budgie 17.04)
I think the one thing that could improve user experience was that the window closes when clicking on "next", it seems like every time you click "next" a new deezer icon is added to the bar. 

search seems to work but sometimes the box seems to lose some of the letters. e.g. if you start typing "Justin Bieber", you may end up with "Juber"

It also seems like you can only add individual tracks to the queue but no full albums.

thank you for getting it this far though.

**Comment by pascalopitz** [comment] 2017-08-14 00:04
What kind of authentication does Deezer use? Password or some link that shows up?

**Comment by MaxJonasG** [comment] 2017-08-14 07:23
Password

**Comment by pascalopitz** [comment] 2017-08-14 11:19
Right! That makes sense. I shall look into it.

**Comment by pascalopitz** [comment] 2017-08-15 05:34
Try v0.1.0-alpha5 plz

**Comment by MaxJonasG** [comment] 2017-08-15 10:08
will do when I get home (sorry, I'm in a different time zone so this always takes a while)

**Comment by pascalopitz** [comment] 2017-08-15 10:11
Don't be sorry ... all good.

**Comment by RhumDiplomatico** [comment] 2017-08-15 12:54
Hi Pascal and Max
Thanks for your voluntary debug
 Pascal you ask "Try v0.1.0-alpha5 plz"
but in this page https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.1.0-alpha5

only extnsions ,'Appimage','deb' , 'zip', or 'tar.gz'



My computer is an amd64 hp dm10

For install 'plz' (Where is this version 'plz '?) ...  I must DÉsinstall my installed version(i don't find the number version ...in tthe menus..)
sorry for my english 
Regards

**Comment by pascalopitz** [comment] 2017-08-15 12:59
Haha, sorry for the confusion, "plz" is a shorthand for "please".

The version is v0.1.0-alpha5, use deb or AppImage, both do the same.

**Comment by MaxJonasG** [comment] 2017-08-15 17:53
the login window now disappears after authorization, as expected.
The search box is still a bit erratic but I believe that is because it refreshes the search results after every letter and if you type to fast  (i.e. while it is still refreshing the list) it deletes the search box string.
I can also still not add whole albums to the queue.

**Comment by pascalopitz** [comment] 2017-08-16 00:13
Please check again with alpha6, which should address the search bar issues and the album playback. If that's working, can I close this issue?

**Comment by MaxJonasG** [comment] 2017-08-16 07:35
I didn't bother with Alph6 and went straight to the released version (which by the way still identifies as alpha5-193)
yes, I can now add whole albums and the search box seems to work okay (still occasional hickups but not as bad as before). I believe this can be closed. Thank you

**Comment by RhumDiplomatico** [comment] 2017-08-16 08:24
HI
I installed the v0.1.0-alpha5 'plz ;-)' .deb
and now i can connect my deezer music service , cool
Still smalls bugs like 'ctrl+-" for zoom out who don't run
or add complèt album
or Button missing for backward, during a search

But I'm happy , good job for this debugging

I will try the 'Alpha 6' and I will write the results

Regards

**Comment by pascalopitz** [comment] 2020-06-01 15:54
Confirmed as working

**Closed by pascalopitz** 2020-06-01 15:54 UTC
Labels: music services
